services:
  - type: web
    name: buy-vs-rent-sim
    env: python
    plan: free
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python -m gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
